# .github/workflows/generate-app-yml.yml
name: Generate Application YML

on:
  workflow_call:
    inputs:
  workflow_dispatch:


jobs:
  setting:
    name: application yml 작성
    runs-on: ubuntu-latest

    steps:
      - name: contract 모듈 application.yml 작성
        run: |
          mkdir -p contract-service/src/main/resources
          cat <<EOF > contract-service/src/main/resources/application.yml
          server:
            port: 8083
          
          eureka:
            client:
              serviceUrl:
                defaultZone: http://discovery-service:${{ secrets.INFRA_EUREKA_SERVER_PORT }}/eureka/
            instance:
              instance-id: "${spring.application.name}:${server.port}:${random.uuid}"
          
          spring:
            application:
              name: contract-service
          
            jackson:
              property-naming-strategy: SNAKE_CASE
          
            jpa:
              open-in-view: false
              hibernate:
                ddl-auto: validate
              properties:
                hibernate:
                  show_sql: false
                  format_sql: false
          
            datasource:
              url: ${{ secrets.DB_MYSQL_URL }}
              driver-class-name: com.mysql.cj.jdbc.Driver
              username: ${{ secrets.DB_MYSQL_USER_NAME }}
              password: ${{ secrets.DB_MYSQL_USER_PASSWORD }}
          
            batch:
              jdbc:
                initialize-schema: always
              job:
                enabled: false
          
            kafka:
              bootstrap-servers:
                - kafka:${{ secrets.INFRA_KAFKA_PORT }}
          
              producer:
                key-serializer: org.apache.kafka.common.serialization.StringSerializer
                value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          
                acks: all
          
                properties:
                  delivery.timeout.ms: 120000
                  linger.ms: 0
                  request.timeout.ms: 30000
                  enable.idempotence: true
                  allow.auto.create.topics: false
          
              consumer:
                group-id: contract-service
                key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          
                properties:
                  spring.json.trusted.packages:
                  allow.auto.create.topics: false
          
          kafka:
            topic:
              contract:
                name: ${{ secrets.KAFKA_TOPIC_NAME_CONTRACT }}
            config:
              topic-partitions: 1
              topic-replications: 1
          
          springdoc:
            swagger-ui:
              path: /api/contracts/swagger-ui
            api-docs:
              path: /api/contracts/v3/api-docs
          
          module:
            member:
              application:
                name: MEMBER-SERVICE
                path:
                  member-exists: /api/internal/members/exist
                  member-info: /api/internal/members
          
          batch:
            settlement:
              size: 500
              settlement-rate: 0.125
              interval: 0 0 3 15 * ? # 매월 15일 새벽 3시
            contract:
              size: 500
              interval: 0 * * * * *
          EOF

  test-setting:
    uses: ./.github/workflows/yml/test-yml-workflow.yml
    secrets: inherit
    with:
      service-name: contract-service