name: cartpost-service ci/cd

on:
  push:
    branches:
      - main
    paths:
      - 'cartpost-service/**'

jobs:
  setting:
    uses: ./.github/workflows/yml/cartpost-yml-workflow.yml
    secrets: inherit

  releasing:
    uses: ./.github/workflows/release-workflow.yml
    secrets: inherit
    with:
      service-name: hexagon-cartpost-service
      service-dir: ./cartpost-service
      file-name: Dockerfile

  deploying:
    needs: releasing
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      service-name: hexagon-cartpost-service
      image-tag: ${{ needs.releasing.outputs.tag_name }}
