name: communication-service ci/cd

on:
  push:
    branches:
      - deploy-test
    paths:
      - 'communication-service/**'

jobs:
  setting:
    uses: ./.github/workflows/yml/communication-yml-workflow.yml
    secrets: inherit
  
  releasing:
    uses: ./.github/workflows/release-workflow.yml
    secrets: inherit
    with:
      service-name: hexagon-communication-service
      service-dir: ./communication-service
      file-name: Dockerfile

  deploying:
    needs: releasing
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      service-name: hexagon-communication-service
      image-tag: ${{ needs.releasing.outputs.tag_name }}
