name: Generate Application YML

on:
  workflow_call:
  workflow_dispatch:


jobs:
  setting:
    name: application yml 작성
    runs-on: ubuntu-latest

    steps:
      - name: gateway 모듈 application.yml 작성
        run: |
          mkdir -p gateway-service/src/main/resources
          cat <<EOF > gateway-service/src/main/resources/application.yml
          server:
            port: 8000
          
          spring:
            application:
              name: gateway-service
          
            cloud:
              gateway:
                server:
                  webflux:
                    routes:
                      #######
                      # CARTPOST SERVICE
                      #######
                      - id: cartpost-service
                        uri: lb://CARTPOST-SERVICE
                        predicates:
                          - Path=/api/commissions/{comissions_code}
                          - Method=GET
                        filters:
                          - GlobalExceptionHandlingFilter
                          - TokenAuthenticationFilter
                      #                - IsSignCheckFilter
          
                      #######
                      # CARTPOST AUTH SERVICE
                      #######
                      - id: cartpost-service
                        uri: lb://CARTPOST-SERVICE
                        predicates:
                          - Path=/api/commissions/**,/api/commissions,/api/carts/**
                      #######
                      # COMMUNICATION SERVICE
                      #######
                      - id: communication-service
                        uri: lb://COMMUNICATION-SERVICE
                        predicates:
                          - Path=/api/chats/**,/api/chats
          
          
                      #######
                      # CONTRACT SERVICE
                      #######
                      - id: contract-service
                        uri: lb://CONTRACT-SERVICE
                        predicates:
                          - Path=/api/contracts/**,/api/contracts,/api/deposits/**,/api/deposits
          
                      - id: member-service-need-auth
                        uri: lb://MEMBER-SERVICE
                        predicates:
                          - Path=/api/members/healthCheck
                        filters:
                          - GlobalExceptionHandlingFilter
                          - TokenAuthenticationFilter
                      #                - IsSignCheckFilter
          
                      #######
                      # MEMBER SERVICE
                      #######
                      - id: member-service
                        uri: lb://MEMBER-SERVICE
                        predicates:
                          - Path=/api/members/**,/api/members,/oauth2/**,/login/**,/login,/api/auth,/api/auth/**
          
                      #######
                      # PAYMENT SERVICE
                      #######
                      - id: payment-service
                        uri: lb://PAYMENT-SERVICE
                        predicates:
                          - Path=/api/payments/**,/api/payments
          
          
                      #######
                      # PROFILE SERVICE
                      #######
                      - id: profile-service
                        uri: lb://PROFILE-SERVICE
                        predicates:
                          - Path=/api/experiences/**,/api/experiences,/api/ratings/**,/api/ratings,/api/resumes/**,/api/resumes,/api/self-promotions/**,/api/self-promotions,/api/tags/**,/api/tags
          
                      #######
                      # SEARCH SERVICE
                      #######
                      - id: search-service
                        uri: lb://SEARCH-SERVICE
                        predicates:
                          - Path=/api/search/**,/api/recommendations/**
          
          cors:
            allowed:
              origin: "${{ secrets.CORS_ALLOWED_ORIGIN }}"
          
          jwt:
            access-token:
              secret: ${{ secrets.JWT_ACCESS_TOKEN_SECRET }}
            claims:
              member-code: ${{ secrets.JWT_CLAIMS_MEMBER_CODE }}
              is-sign: ${{ secrets.JWT_CLAIMS_IS_SIGNED }}
          
          
          eureka:
            client:
              serviceUrl:
                defaultZone: http://discovery-service:${{ secrets.INFRA_EUREKA_SERVER_PORT }}/eureka/
            instance:
              instance-id: "${spring.application.name}:${server.port}:${random.uuid}"         
          EOF