#Test 전용 yml 파일 작성
name: Generate Application-test properties

on:
  workflow_call:
    inputs:
      service-name:        # <- 원하는 input 추가
        description: '서비스 이름'
        type: string
        required: true     # 필수 여부



jobs:
  test-setting:
    name: application-test properties 작성
    runs-on: ubuntu-latest

    steps:
      - name: ${{ inputs.service-name }} 모듈 application.properties 작성
        run: |
          mkdir -p ${{ inputs.service-name }}/src/main/resources
          cat <<EOF > ${{ inputs.service-name }}/src/main/resources/application-test.properties
          spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL;IGNORECASE=TRUE;INIT=SET REFERENTIAL_INTEGRITY FALSE
          spring.datasource.driver-class-name=org.h2.Driver
          spring.datasource.username=sa
          spring.datasource.password=
          spring.jpa.hibernate.ddl-auto=create-drop
          spring.jpa.show-sql=false
          spring.jpa.properties.hibernate.format_sql=false
          spring.jpa.defer-datasource-initialization=true
          spring.h2.console.enabled=false
          spring.datasource.platform=h2
          spring.sql.init.mode=never
          spring.sql.init.platform=h2
          spring.jpa.defer-datasource-initialization=false
          EOF