#Test 전용 yml 파일 작성
name: Generate Application-test YML

on:
  workflow_call:
    inputs:
      service-name:        # <- 원하는 input 추가
        description: '서비스 이름'
        type: string
        required: true     # 필수 여부



jobs:
  test-setting:
    name: application-test yml 작성
    runs-on: ubuntu-latest

    steps:
      - name: ${{ inputs.service-name }} 모듈 application.yml 작성
        run: |
            mkdir -p ${{ inputs.service-name }}/src/main/resources
            cat <<EOF > ${{ inputs.service-name }}/src/main/resources/application-test.yml
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL;IGNORECASE=TRUE;INIT=SET REFERENTIAL_INTEGRITY FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true

  h2:
    console:
      enabled: false
EOF